### ISSUE TITLE
Consider adding typescript support

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/bcp-redux#29]
I have no clear approach to migrating the codebase and this is not urgent, I just want to collect some ideas on how it can be done with redux, especially the type inference with actions and state. Since most data comes from @iov/core with types provided, it makes it easy to check the wiring full-stack up to the components

Here are some links that provide helpers, although they are quite opinionated with eg. redux-saga or redux-observables instead of the promise middleware approach currently used. I would not take all the suggestions, but the examples of how to create typesafe actions and reducers are nice, especiallyhttps://github.com/piotrwitek/typesafe-actions/blob/master/README.md#--the-actions and the reducers section below it.

* https://medium.com/@resir014/redux-4-typescript-2-9-a-type-safe-approach-7f073917b803
* https://github.com/piotrwitek/react-redux-typescript-guide

Ideas? Links? Suggestions? Opinions?

**Comment by rudi-cilibrasi** [comment]
I love the idea of typescript support specifically in the redux actions, reducers, and selectors!
It would be a big help.

My only concern is when and where to add it and how easily it can be removed. I would want to have a version that did not have typescript for build compatibility testing. Not sure if that's easy / possible to make using regular tsc tools automatically.  But in principle I love static types and they are the main way we can improve the situation in reducer/selector/action subdirs. In practice we want to do quick react native, PWA, android embedded WebView tests and I am not familiar enough with JS build details to know if it would interfere or not.

**Comment by rudi-cilibrasi** [comment]
About `redux-saga`, it was a lot cooler before async and await allowed a more natural kind of dispatch chaining within the core language. Now it is mostly redundant because the most common case (linear sequence of actions) are better covered by keywords.

**Comment by rudi-cilibrasi** [comment]
For advanced uses (like high overlap) redux-saga can be useful as explained here. https://thecodebarbarian.com/redux-saga-vs-async-await.html  we aren't really doing those yet though and don't need to before MVP and don't want to add an additional pattern that increases source code variation for the purpose of latency performance at this phase. correctness first for now. for more about async await functioanlity overlap https://github.com/redux-saga/redux-saga/issues/1373

**Comment by ethanfrey** [comment]
> My only concern is when and where to add it and how easily it can be removed. I would want to have a version that did not have typescript for build compatibility testing. Not sure if that's easy / possible to make using regular tsc tools automatically. But in principle I love static types and they are the main way we can improve the situation in reducer/selector/action subdirs. In practice we want to do quick react native, PWA, android embedded WebView tests and I am not familiar enough with JS build details to know if it would interfere or not.

The build process in @iov/core is a nice example. Rather than webpacking doing all the magic, it is split into sections.

- tslint (annoying but useful for standard code)
- tsc (compile src/*ts -> build/*.js)
- webpack (compile build/*.js -> dist/bunde.js)

The nice issue here is the output of tsc is guaranteed to be vanilla es6 (or es5 if you really want), which can be fed into most other tools (webpack, react native, etc.) without even worrying about babel anymore. In essence, `tsc` replaces `babel` and runs as a separate step in the build process.

Hopefully this is a solution to `I would want to have a version that did not have typescript for build compatibility testing.`

If so, I may consider moving it in, first on actions, then in reducers. My thought was to start with an eg. `ts` dir next to `src` and then have `ts/actions/**.ts` compile into `src/actions/**.js`, so the rest of the code would work as is. It does add one more step to the build process and some compile-time overhead, but should be completely compatible with current build system, allowing us to slowly opt into types.

Oh, and since promises are mostly just taking @iov/core results and performing a bit of filtering/manipulation, most of those types come for free :)

**Comment by rudi-cilibrasi** [comment]
the general plan sounds good but i can't afford to lose `.mjs` compatibility at this time as we finish up mvp 1.0.

**Comment by rudi-cilibrasi** [comment]
pausing until we unfreeze with discussion between Ethan,Rudi,Isabella and settled concerns
