### ISSUE TITLE
Persist user profiles separately from redux store

### ISSUE THREAD

**Issue by rudi-cilibrasi** [iov-one/bcp-redux#33]
we already save and load `blockchain` and `purseNonSense` using actions and during boot up.

we need to add `purseSense` that behaves almost identically to `purseNonSense` except that it encrypts the persistent store so that it's more difficult to tamper. as part of this ticket:
1. make a new directory in reducer `purseSense` like `purseNonSense` and containing at least enough to show something in the `JSONTree` that can be saved or loaded
2. show that loading works during boot or after a password is entered to unlock, etc.
3. show that saving works (as action) and is encrypted

**Comment by Isabello** [comment]
this branch addresses it. PR soon https://github.com/iov-one/bcp-redux/tree/implement-profile-save
