### ISSUE TITLE
Update chainId-related selector names

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/bcp-redux#47]
From Rudi:

so it would go
1. purseNonSense.settings 2. initialize each in writer then blockchain interleaved
tey are not technically redundant correct?
maybe best names are `blockchainEverSeenChainIds`
`transientConnectedChainIds`
`purseNonSenseSettingsChainIdsUrlsMap`
so if we reconfigure to reduce chainIds

---

So, `transientConnectedChainIds` pulls from transient.connectionManager (sorted list of reader chainids)
`blockchainEverSeenChainIds` pulls from blockchain (all state we have seen and captured)
`purseNonSenseSettingsChainIdsUrlsMap` (maybe renamed?? list of all settings for chains we wish to connect to)

**Comment by rudi-cilibrasi** [comment]
also we add suffix `Selector` in each
